name: supply-chain-demo
channels:
  - conda-forge
dependencies:
- pip
- pydantic
- coverage
- mypy
- flake8
- pymc3
- pystan==2.19.1.1
- prophet
- theano-pymc 
- mkl 
- mkl-service
- pip:
  - streamlit
  - mip
  - ortools
  - graphviz
  - simpy
  - pandas
  - altair


